Fixes unit-tests for Vagrant
os.Link to "copy" the config file to /tmp fails on vagrant because it
crosses over different file systems. This patch simply copies the file
instead.

Before:
2017/01/17 15:12:43 [DEBUG] Retrieving client config
--- FAIL: TestEnrollCLI (10.01s)
        client_test.go:60: Failed to register, err:  Failed to load client config file [open /tmp/client196787572/cop_client.json: no such file or directory]; not sending
...
FAIL    github.com/hyperledger/fabric-cop/cli/client    10.048s
error: exit status 1

After:
ok      github.com/hyperledger/fabric-cop/cli/client    10.172s coverage: 76.5% of statements

Change-Id: I2a64f93cb62fbc5abb62df6a4cd980702f0e01bc
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>