[FAB-6328] Fix cleanup of unit-tests temp files
This change introduces a more systematic policy of removing files
generated by each test so that they do not pollute the environment
they are run in and they are effectively independent from one
another. This includes both files created locally and in os.TempDir.

For instance, before this change one cannot run TestCLIClient twice:

$ go test -v -run ^TestCLIClient\$
=== RUN   TestCLIClient
--- PASS: TestCLIClient (8.56s)
	client_test.go:223: GetCAInfo error Failed to create keystore
directory: mkdir /home/lehors/Projects/Go/src/github.com/hyperledger/
fabric-ca/lib/: invalid argument
[...]
	client_test.go:436: Client Enroll error Failure generating CS
R: Invalid algorithm: dsa
PASS
ok  	github.com/hyperledger/fabric-ca/lib	8.575s
lehors:~/Projects/Go/src/github.com/hyperledger/fabric-ca/lib
$ go test -v -run ^TestCLIClient\$
=== RUN   TestCLIClient
--- FAIL: TestCLIClient (2.49s)
	client_test.go:223: GetCAInfo error Failed to create keystore
 directory: mkdir /home/lehors/Projects/Go/src/github.com/hyperledger
/fabric-ca/lib/: invalid argument
	client_test.go:231: GetCAInfo error address localhost:[:7054:
 too many colons in address
	client_test.go:240: GetCAInfo error POST failure of request:
POST http:///cainfo
		Authorization:
		{}: Post http:///cainfo: http: no Host in request URL
	client_test.go:255: CheckEnrollment error <nil>
	client_test.go:257: testRegister check enrollment should have
 failed - client not enrolled
FAIL
exit status 1
FAIL	github.com/hyperledger/fabric-ca/lib	2.496s

The reason for the failure on the second run is merely that the first
run left some temporary directory behind that trips the second run.

With this change, all files and directories created by each test are
deleted at the end of each test, even when the test fails half way
through.

Change-Id: Icb7da9df150774387762cbc116a3445ffde02b7d
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>